import { HerdrError } from './protocol';
import { DEFAULT_SESSION } from './session';
import { shellCommand, withPath } from './shell';

/**
 * The machines saved on a host: other computers running herdr that the host
 * reaches over SSH (`herdr machine add <ssh-target>`). The herdr desktop app on
 * the host shows their sessions beside its own; the app does the same by
 * listing them here and jumping through the host to each (see `machine.ts`).
 * Nothing about them is configured on the phone.
 */
export interface HostMachine {
  /** herdr's id for the machine. Never contains a slash. */
  id: string;
  /** Its name, as herdr's own clients show it ("klaw"). */
  label: string;
  /** The SSH destination the HOST resolves: an alias in its `~/.ssh/config`, usually. */
  target: string;
  /** The herdr session on the machine; `default` when herdr names none. */
  session: string;
  /** A disabled machine stays saved on the host and is not shown. */
  enabled: boolean;
}

export interface MachineList {
  machines: HostMachine[];
  /** One line per row that could not be read, so a bad row is visible rather than silently gone. */
  skipped: string[];
}

/** The argv that lists the machines, as JSON. */
export function machineListArgv(herdrPath: string): string[] {
  return [herdrPath, 'machine', 'list', '--json'];
}

/** `herdr machine list --json`, as the host runs it. */
export function machineListCommand(herdrPath: string): string {
  return withPath(shellCommand(machineListArgv(herdrPath)));
}

/**
 * Read `herdr machine list --json`.
 *
 * Measured on herdr 0.8 (Gimel, 2026-10-09):
 *
 *   [{"id":"6eff…","label":"klaw","target":"klaw","session":"default","enabled":true,"selected":true}]
 *
 * Tolerant, because a host's herdr may be newer than the app: unknown keys are
 * ignored, a missing `session` is `default`, a missing `enabled` is true, a
 * missing `label` is the target, and a row that cannot be used is skipped and
 * reported, never the whole list's failure. A bare array, `{machines: […]}` and
 * a `{result: …}` envelope around either are all accepted.
 *
 * @throws {HerdrError} when the output is not JSON or holds no list at all.
 */
export function parseMachineList(output: string): MachineList {
  const text = output.trim();
  if (text.length === 0) return { machines: [], skipped: [] };

  let parsed: unknown;
  try {
    parsed = JSON.parse(text) as unknown;
  } catch {
    throw new HerdrError('unparseable_response', "The host's machine list wasn't JSON.");
  }

  const rows = listIn(parsed) ?? listIn(field(parsed, 'result'));
  if (rows === null) {
    throw new HerdrError('unparseable_response', "The host's machine list wasn't a list.");
  }

  const machines: HostMachine[] = [];
  const skipped: string[] = [];
  const seen = new Set<string>();
  rows.forEach((row, index) => {
    const machine = machineFrom(row);
    if (typeof machine === 'string') {
      skipped.push(`machine ${index + 1}: ${machine}`);
    } else if (seen.has(machine.id)) {
      skipped.push(`machine ${index + 1}: ${machine.id} is listed twice`);
    } else {
      seen.add(machine.id);
      machines.push(machine);
    }
  });
  return { machines, skipped };
}

function listIn(value: unknown): unknown[] | null {
  if (Array.isArray(value)) return value;
  const inner = field(value, 'machines');
  return Array.isArray(inner) ? inner : null;
}

/** One row as a machine, or why it cannot be one. */
function machineFrom(row: unknown): HostMachine | string {
  if (typeof row !== 'object' || row === null || Array.isArray(row)) return 'not an object';
  const id = text(field(row, 'id'));
  const target = text(field(row, 'target'));
  if (id === null) return 'no id';
  if (id.includes(MACHINE_SEPARATOR)) return `id ${id} has a slash`;
  if (target === null) return `${id} has no target`;
  const enabled = field(row, 'enabled');
  if (enabled !== undefined && typeof enabled !== 'boolean') return `${id} has an unreadable enabled flag`;
  return {
    id,
    label: text(field(row, 'label')) ?? target,
    target,
    session: text(field(row, 'session')) ?? DEFAULT_SESSION,
    enabled: enabled ?? true,
  };
}

function text(value: unknown): string | null {
  return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null;
}

function field(value: unknown, key: string): unknown {
  return typeof value === 'object' && value !== null ? (value as Record<string, unknown>)[key] : undefined;
}

// MARK: - Connection ids

/**
 * Between a host's id and a machine's in a machine connection's id. Neither
 * can contain it: host ids are generated by the app, and a machine id with a
 * slash is skipped when the list is read.
 */
export const MACHINE_SEPARATOR = '/';

/**
 * The id of a machine connection: derived, never saved. Everything keyed by
 * connection id (the thread cache, tail cursors, drafts, pins, mutes) works
 * unchanged with it, and everything of a host's machines sits under the
 * prefix `${hostId}/`, so forgetting a host can drop it all at once.
 */
export function machineConnectionId(hostId: string, machineId: string): string {
  return `${hostId}${MACHINE_SEPARATOR}${machineId}`;
}

/** The host and machine of a machine connection's id, or null for any other id. */
export function splitMachineConnectionId(id: string): { hostId: string; machineId: string } | null {
  const parts = id.split(MACHINE_SEPARATOR);
  if (parts.length !== 2) return null;
  const [hostId = '', machineId = ''] = parts;
  return hostId.length > 0 && machineId.length > 0 ? { hostId, machineId } : null;
}

/** Whether `key` belongs to one of `hostId`'s machines: `${hostId}/…`. */
export function isUnderHost(key: string, hostId: string): boolean {
  return key.startsWith(`${hostId}${MACHINE_SEPARATOR}`);
}

// MARK: - Refresh cadence

/**
 * How often the chat list's poll also asks the host for its machines.
 *
 * A machine is added or disabled at the host's keyboard, rarely, and the list
 * is cached on the phone, so its rows are there from launch. A minute keeps a
 * newly saved machine prompt enough without one more round-trip on every 3 s
 * tick; a pull to refresh or coming back to the app asks at once.
 */
export const MACHINE_LIST_INTERVAL_MS = 60_000;

/** Whether the machine list is due, given when it was last asked (null: never, or asked for). */
export function machineListDue(lastCheck: number | null, now: number): boolean {
  return lastCheck === null || now - lastCheck >= MACHINE_LIST_INTERVAL_MS;
}
